{% set version = "0.4.0" %}
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.8").split(".")[0] | int %}
{% endif %}

package:
  name: pyg-lib
  version: {{ version }}

source:
  - url: https://github.com/pyg-team/pyg-lib/archive/refs/tags/{{ version }}.tar.gz
    sha256: 6a515815f69f925a0ba15e743ac071629e1fd1ae9c46576db8b7f91ab40a8eac
    patches:
      - patches/0001-fix-cmake.patch
      # due to https://github.com/conda-forge/pytorch-cpu-feedstock/issues/357
      - patches/0002-look-harder-for-pytorch.patch

  - folder: third_party/cutlass
    git_url: https://github.com/NVIDIA/cutlass.git
    git_rev: 6f47420213f757831fae65c686aa471749fa8d60

  - folder: third_party/METIS
    git_url: https://github.com/KarypisLab/METIS.git
    git_rev: 22008804e8c9b78893ae10a94c0d8b4b592438b4

  - folder: third_party/parallel-hashmap
    git_url: https://github.com/greg7mdp/parallel-hashmap.git
    git_rev: 01ea8093e6d0293ea252e8027c17d7dff26a9c9f

build:
  number: 2
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  # Only build for CUDA >=11.8
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                             # [cuda_compiler_version not in (undefined, 'None')]
    - python                                             # [build_platform != target_platform]
    - cross-python_{{ target_platform }}                 # [build_platform != target_platform]
    - cmake
    - ninja        # [unix]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - parallel-hashmap
    - cutlass                        # [cuda_compiler_version not in (undefined, 'None')]
  host:
    - python
    - pip
    - setuptools
    - pytorch
    - pytorch =*={{ torch_proc_type }}*
    - cuda-version =={{ cuda_compiler_version }}  # [cuda_compiler_version not in (undefined, 'None')]
    {% if cuda_major >= 12 %}
    - cuda-cudart-dev
    # No cuda-driver-dev in windows
    - cuda-driver-dev  # [linux]
    - cuda-nvrtc-dev
    - cuda-nvtx-dev
    - cuda-profiler-api
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    - nvtx-c
    {% endif %}
  run:
    - python
    - parallel-hashmap
    - triton                                 # [linux and cuda_compiler_version not in (undefined, 'None')]
    - cutlass                                # [cuda_compiler_version not in (undefined, 'None')]
  run_constrained:
    # additional run constraint to the one from the (version-only) run_export;
    # constraining the CPU builds to CPU pytorch isn't 100% necessary, but cleaner
    - pytorch =*={{ torch_proc_type }}*

test:
  imports:
    - pyg_lib
  requires:
    - pytest
  source_files:
    - test/
  commands:
    - pytest

about:
  home: https://github.com/pyg-team/pyg-lib
  summary: Low-Level Graph Neural Network Operators for PyG
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pyg-team/pyg-lib

extra:
  recipe-maintainers:
    - rusty1s
    - RaulPPelaez
